-- MySQL Script generated by MySQL Workbench
-- Sat Sep 28 23:47:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema a111
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema a111
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `a111` DEFAULT CHARACTER SET utf8mb4 ;
USE `a111` ;

-- -----------------------------------------------------
-- Table `a111`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`person` ;

CREATE TABLE IF NOT EXISTS `a111`.`person` (
  `name` VARCHAR(30) NULL,
  `cnic` VARCHAR(30) NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `image` TEXT(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`address` ;

CREATE TABLE IF NOT EXISTS `a111`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `address_city` VARCHAR(50) NULL DEFAULT 'lahore',
  `address_town` VARCHAR(50) NULL,
  `address_street_no` INT(11) NULL DEFAULT NULL,
  `address_house_no` INT(11) NULL DEFAULT NULL,
  `person_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_address_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `a111`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`location` ;

CREATE TABLE IF NOT EXISTS `a111`.`location` (
  `id` INT NOT NULL,
  `logitude` FLOAT NULL,
  `lagitude` FLOAT NULL,
  `expire` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`user` ;

CREATE TABLE IF NOT EXISTS `a111`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(30) NULL,
  `person_id` INT(11) NOT NULL,
  `isExpire` DATETIME NULL DEFAULT NULL,
  `isowner` TINYINT NULL DEFAULT 0,
  `company_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_person1_idx` (`person_id` ASC),
  INDEX `fk_user_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_user_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `a111`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `a111`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`company` ;

CREATE TABLE IF NOT EXISTS `a111`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `expire` DATETIME NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_company_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `a111`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`catering`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`catering` ;

CREATE TABLE IF NOT EXISTS `a111`.`catering` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `expire` DATETIME NULL,
  `image` VARCHAR(45) NULL,
  `location_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_catering_location1_idx` (`location_id` ASC),
  INDEX `fk_catering_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_catering_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `a111`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_catering_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `a111`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`number` ;

CREATE TABLE IF NOT EXISTS `a111`.`number` (
  `number` VARCHAR(30) NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `is_number_active` TINYINT NULL DEFAULT 1,
  `person_id` INT(11) NOT NULL,
  `catering_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_number_person1_idx` (`person_id` ASC),
  INDEX `fk_number_catering1_idx` (`catering_id` ASC),
  CONSTRAINT `fk_number_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `a111`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_number_catering1`
    FOREIGN KEY (`catering_id`)
    REFERENCES `a111`.`catering` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`orderTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`orderTable` ;

CREATE TABLE IF NOT EXISTS `a111`.`orderTable` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `total_amount` INT(11) NULL DEFAULT 0,
  `order_comments` TEXT NULL DEFAULT NULL,
  `total_person` INT NULL,
  `is_active` INT NULL DEFAULT 0,
  `destination_date` DATE NULL,
  `booking_date` DATE NULL,
  `destination_time` TIME(6) NULL,
  `address_id` INT(11) NULL,
  `extre_charges` INT NULL,
  `person_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_address1_idx` (`address_id` ASC),
  INDEX `fk_order_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_order_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `a111`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `a111`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`dish_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`dish_type` ;

CREATE TABLE IF NOT EXISTS `a111`.`dish_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `isExpire` DATETIME NULL DEFAULT NULL,
  `catering_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dish_type_catering1_idx` (`catering_id` ASC),
  CONSTRAINT `fk_dish_type_catering1`
    FOREIGN KEY (`catering_id`)
    REFERENCES `a111`.`catering` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`dish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`dish` ;

CREATE TABLE IF NOT EXISTS `a111`.`dish` (
  `name` VARCHAR(30) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(300) NULL,
  `dish_type_id` INT NOT NULL,
  `isExpire` DATETIME NULL DEFAULT NULL,
  `catering_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dish_dish_type1_idx` (`dish_type_id` ASC),
  INDEX `fk_dish_catering1_idx` (`catering_id` ASC),
  CONSTRAINT `fk_dish_dish_type1`
    FOREIGN KEY (`dish_type_id`)
    REFERENCES `a111`.`dish_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dish_catering1`
    FOREIGN KEY (`catering_id`)
    REFERENCES `a111`.`catering` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`attribute` ;

CREATE TABLE IF NOT EXISTS `a111`.`attribute` (
  `name` VARCHAR(45) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `dish_id` INT NOT NULL,
  `isExpire` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attribute_dish1_idx` (`dish_id` ASC),
  CONSTRAINT `fk_attribute_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `a111`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`dish_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`dish_detail` ;

CREATE TABLE IF NOT EXISTS `a111`.`dish_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `describe` TEXT(300) NULL,
  `price` INT NULL,
  `expire_date` DATETIME NULL,
  `quantity` INT NULL,
  `dish_id` INT NOT NULL,
  `orderTable_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dish_detail_dish1_idx` (`dish_id` ASC),
  INDEX `fk_dish_detail_orderTable1_idx` (`orderTable_id` ASC),
  CONSTRAINT `fk_dish_detail_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `a111`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dish_detail_orderTable1`
    FOREIGN KEY (`orderTable_id`)
    REFERENCES `a111`.`orderTable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`attribute_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`attribute_name` ;

CREATE TABLE IF NOT EXISTS `a111`.`attribute_name` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `attribute_id` INT NOT NULL,
  `dish_detail_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attribute_name_attribute1_idx` (`attribute_id` ASC),
  INDEX `fk_attribute_name_dish_detail1_idx` (`dish_detail_id` ASC),
  CONSTRAINT `fk_attribute_name_attribute1`
    FOREIGN KEY (`attribute_id`)
    REFERENCES `a111`.`attribute` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attribute_name_dish_detail1`
    FOREIGN KEY (`dish_detail_id`)
    REFERENCES `a111`.`dish_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`payment` ;

CREATE TABLE IF NOT EXISTS `a111`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `nameCustomer` VARCHAR(45) NULL,
  `receive` DATETIME NULL,
  `personality` TEXT(300) NULL,
  `rating` INT NULL,
  `IsReturn` TINYINT NULL,
  `user_id` INT NOT NULL,
  `orderTable_id` INT(11) NOT NULL,
  `sendingStatus` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_user1_idx` (`user_id` ASC),
  INDEX `fk_payment_orderTable1_idx` (`orderTable_id` ASC),
  CONSTRAINT `fk_payment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `a111`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_orderTable1`
    FOREIGN KEY (`orderTable_id`)
    REFERENCES `a111`.`orderTable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`transfer` ;

CREATE TABLE IF NOT EXISTS `a111`.`transfer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Isconfirm` DATETIME NULL,
  `senderTimeDate` DATETIME NULL,
  `payment_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `Isget` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transfer_payment1_idx` (`payment_id` ASC),
  INDEX `fk_transfer_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_transfer_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `a111`.`payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `a111`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`hall`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`hall` ;

CREATE TABLE IF NOT EXISTS `a111`.`hall` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `min_guests` INT NULL,
  `max_guests` INT NULL,
  `function_per_Day` VARCHAR(45) NULL,
  `noOfPartitions` INT NULL,
  `ownParking` TINYINT NULL,
  `expire` DATETIME NULL,
  `image` TEXT(200) NULL,
  `hallType` VARCHAR(45) NULL,
  `location_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hall_location1_idx` (`location_id` ASC),
  INDEX `fk_hall_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_hall_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `a111`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hall_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `a111`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`images` ;

CREATE TABLE IF NOT EXISTS `a111`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` TEXT(200) NULL,
  `expire` DATETIME NULL,
  `catering_id` INT NULL,
  `hall_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_catering1_idx` (`catering_id` ASC),
  INDEX `fk_images_hall1_idx` (`hall_id` ASC),
  CONSTRAINT `fk_images_catering1`
    FOREIGN KEY (`catering_id`)
    REFERENCES `a111`.`catering` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_images_hall1`
    FOREIGN KEY (`hall_id`)
    REFERENCES `a111`.`hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`systemITems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`systemITems` ;

CREATE TABLE IF NOT EXISTS `a111`.`systemITems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `images` VARCHAR(200) NULL,
  `expire` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`item` ;

CREATE TABLE IF NOT EXISTS `a111`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `image` VARCHAR(200) NULL,
  `expire` DATETIME NULL,
  `prizeSytem` INT NULL,
  `hall_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_hall1_idx` (`hall_id` ASC),
  CONSTRAINT `fk_item_hall1`
    FOREIGN KEY (`hall_id`)
    REFERENCES `a111`.`hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`hallprice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`hallprice` ;

CREATE TABLE IF NOT EXISTS `a111`.`hallprice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `month` VARCHAR(45) NULL,
  `isFood` TINYINT NULL,
  `price` INT NULL,
  `describe` TEXT(200) NULL,
  `dayTime` INT NULL,
  `expire` DATETIME NULL,
  `hall_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hallprice_hall1_idx` (`hall_id` ASC),
  CONSTRAINT `fk_hallprice_hall1`
    FOREIGN KEY (`hall_id`)
    REFERENCES `a111`.`hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`menu` ;

CREATE TABLE IF NOT EXISTS `a111`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dishname` VARCHAR(45) NULL,
  `image` TEXT(100) NULL,
  `expire` DATETIME NULL,
  `hallprice_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_hallprice1_idx` (`hallprice_id` ASC),
  CONSTRAINT `fk_menu_hallprice1`
    FOREIGN KEY (`hallprice_id`)
    REFERENCES `a111`.`hallprice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`orderDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`orderDetail` ;

CREATE TABLE IF NOT EXISTS `a111`.`orderDetail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderTable_id` INT(11) NOT NULL,
  `hall_id` INT NULL,
  `catering_id` INT NULL,
  `isHallOrCatering` TINYINT NULL,
  `orderDetailcol` VARCHAR(45) NULL,
  `hallprice_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orderDetail_orderTable1_idx` (`orderTable_id` ASC),
  INDEX `fk_orderDetail_hall1_idx` (`hall_id` ASC),
  INDEX `fk_orderDetail_catering1_idx` (`catering_id` ASC),
  INDEX `fk_orderDetail_hallprice1_idx` (`hallprice_id` ASC),
  CONSTRAINT `fk_orderDetail_orderTable1`
    FOREIGN KEY (`orderTable_id`)
    REFERENCES `a111`.`orderTable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderDetail_hall1`
    FOREIGN KEY (`hall_id`)
    REFERENCES `a111`.`hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderDetail_catering1`
    FOREIGN KEY (`catering_id`)
    REFERENCES `a111`.`catering` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderDetail_hallprice1`
    FOREIGN KEY (`hallprice_id`)
    REFERENCES `a111`.`hallprice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`order_items` ;

CREATE TABLE IF NOT EXISTS `a111`.`order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `expire` DATETIME NULL,
  `item_id` INT NULL,
  `orderDetail_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_items_item1_idx` (`item_id` ASC),
  INDEX `fk_order_items_orderDetail1_idx` (`orderDetail_id` ASC),
  CONSTRAINT `fk_order_items_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `a111`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_orderDetail1`
    FOREIGN KEY (`orderDetail_id`)
    REFERENCES `a111`.`orderDetail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`systemDishType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`systemDishType` ;

CREATE TABLE IF NOT EXISTS `a111`.`systemDishType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `isExpire` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`systemDish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`systemDish` ;

CREATE TABLE IF NOT EXISTS `a111`.`systemDish` (
  `name` VARCHAR(30) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(300) NULL,
  `isExpire` DATETIME NULL DEFAULT NULL,
  `systemDishType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_systemDish_systemDishType1_idx` (`systemDishType_id` ASC),
  CONSTRAINT `fk_systemDish_systemDishType1`
    FOREIGN KEY (`systemDishType_id`)
    REFERENCES `a111`.`systemDishType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a111`.`SystemAttribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a111`.`SystemAttribute` ;

CREATE TABLE IF NOT EXISTS `a111`.`SystemAttribute` (
  `name` VARCHAR(45) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `isExpire` DATETIME NULL DEFAULT NULL,
  `systemDish_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SystemAttribute_systemDish1_idx` (`systemDish_id` ASC),
  CONSTRAINT `fk_SystemAttribute_systemDish1`
    FOREIGN KEY (`systemDish_id`)
    REFERENCES `a111`.`systemDish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
